repos:
- repo: meta
  hooks:
  - id: check-useless-excludes
  - id: check-hooks-apply
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v18.1.3
  hooks:
  - id: clang-format
    'types_or': [c++, c]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: destroyed-symlinks
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: fix-byte-order-marker
  - id: mixed-line-ending
    args: [--fix=lf]
  - id: trailing-whitespace
