name: Dispatch Release 
on:
  push:
    tags:
    - v*
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send repository dispatch
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/isri-aist/cdadance-superbuild/dispatches \
            -d '{"event_type":"dispatch-cdadance"}'
